config/routes.rb
Rss::Application.routes.draw do

  root :to => 'channels#index'
  
  resource :login, :controller => :login

  resources :channels do
    resources :posts do
      match 'image' => 'posts#show_image'
    end
    resources :subscriptions
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :posts, :dependent => :destroy
  has_many :subscriptions, :dependent => :destroy
  validates :name, :presence => true

  def subscribe(username)
    unless subscribed? username
      return subscriptions.build :username => username
    else
      return false
    end
  end

  def subscribed?(username)
    !!find_subscription(username)
  end

  def find_subscription(username)
  	return Subscription.find_by_username username
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :channel
  attr_accessible :content, :title, :image, :author

  validates :title, :content, :presence => true
  
  after_save :send_broadcast

  def author=(author)
    if author == '' or author == nil
      @author = 'anonymous'
    else
      @author = author
    end
  end

  def author
  	if @author == '' or @author == nil
      'anonymous'
    else
      @author
    end
  end

  private 
    def send_broadcast
      begin
        push_client = ::RSS::PushClient.new "http://10.32.152.234:8080/Androidpn/ws/nfws"

        push_client.send_broadcast '', title, content, ''
      rescue Exception
        logger.warn "Cannot connect to the push server...."
      end
    end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :channel
  attr_accessible :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  
  # before_filter :require_login
  
  include Rss::UserRepository

  private
    def current_username
      session[:username]
    end

    def logged_in?
      !!current_username
    end

    def require_login
      @current_username = current_username
      redirect_to login_url unless logged_in?   
    end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels, content_type: 'text/json' }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.rss
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    puts "****************#{params}"
    @channel = Channel.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = Channel.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  skip_before_filter :require_login, :only => [:show, :create]

  def show
  end

  def create
  	if params[:username] == 'admin' and params[:password] == 'admin'
      	session[:username] = params[:username]
      	redirect_to :root
      else 
      	@login_error_msg = "Login Failed"
      	render 'show'
    end
  end

  def destroy
  	session.clear
    redirect_to login_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @channel = Channel.find params[:channel_id]
    @post = @channel.posts.build
  end

  def create
    @channel = Channel.find params[:channel_id]
    @post = @channel.posts.build params[:post] do |p|
      p.image = params[:image].read if params[:image]
    end
    @post.author = 'current_username'
    respond_to do |format|
      if @post.save
        format.html { redirect_to channel_post_path(@channel, @post), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @post = Post.find params[:id] 
  end

  def show_image
    @post = Post.find params[:post_id]
    send_data @post.image, :type => 'image/jpeg', :disposition => :inline, :content_length => @post.image.length
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]

    respond_to do |format|
      if @post.update_attributes params[:post]
        format.html { redirect_to channel_post_path(@post.channel, @post), notice: 'Post was successfully updated' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    Post.delete params[:id]

    redirect_to channel_path(params[:channel_id])
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def create
  	channel = Channel.find params[:channel_id]
  	subscription = channel.subscribe current_username

  	respond_to do |format|
  	  if subscription
  	  	if subscription.save
  	  	  format.html { redirect_to channels_path, :notice => "You have successfully subscribe the channel: #{channel.name}" }
  	  	else
  	  	  render 'channels#index', :notice => 'cannot subscribe this channel'
  	  	end
  	  else
  	  	format.html { redirect_to channels_path, :notice => 'You have already subscribe this channel' }
  	  end
  	end
  end

  def destroy
    respond_to do |format|
      if Subscription.delete params[:id]
      	format.html { redirect_to channels_path, :notice => 'Subscription cancelled' }
      else
      	format.html { redirect_to channels_path, :notice => 'Cannot cancel subscription' }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/security_helper.rb
module SecurityHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<% if notice %>
<div id="notice">
  <div class="clear_notice_icon">x</div>
  <%= notice %>
</div>
<% end %>

<div class="new_channel_link">
  <%= link_to 'New Channel', new_channel_path %>
</div>
<div id="channel_list">
  <% @channels.each do |channel| %>
  <div class="channel_entry">
    <div class="channel_name">
      <h3>
        <%= "#{channel.name}" %>
        <%= link_to channel_path(channel, :rss) do %>
          <%= image_tag 'rss.gif', :title => 'RSS Feed' %>
        <% end %>
      </h3>
      <div class="channel_operations">
        <%= link_to 'View', channel %>
        <%= link_to 'Edit', edit_channel_path(channel) %>
        <%= link_to 'Delete', channel, :method => :delete, :confirm => 'Will remove the channel and all articles in it, are you sure?' %>
        <%= link_to 'Add Article', new_channel_post_path(channel) %>
        <% if channel.subscribed? @current_username %>
          <%= link_to 'Cancel Subscription', 
                      channel_subscription_path(channel, channel.find_subscription(@current_username)), 
                      :method => :delete 
          %>
        <% else %>
          <%= link_to 'Subscribe', channel_subscriptions_path(channel), :method => :post %>
        <% end %>
      </div>
    </div>
    <div class="clear_float"></div>
    <div class="channel_description">
      <span><%= channel.description %></span>
    </div>
  </div>
  <% end %>
</div>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<%= link_to 'Back', channels_path %>
<% @channel.posts.order.order('created_at desc').each do |post| %>
<div class="article">
  <div class="article_title">
    <div class="article_title_text">
      <%= link_to post.title, channel_post_path(post) %>
    </div>
    <div class="article_pubDate"><%= post.created_at.to_s(:db) %></div>
    <div class="clear_float"></div>
  </div>
  <div class="article_content">
    <%= post.content %>
  </div>
  <% if post.image %>
  <div class="article_image">
    <%= image_tag channel_post_image_path(@channel, post)%>
  </div>
  <div class="clear_float"></div>
  <% end %>
  <div class="article_operations">
    <ul>
      <li>
        <%= link_to 'Edit', edit_channel_post_path(@channel, post) %>
      </li>
      <li>
        <%= link_to 'View', channel_post_path(@channel, post) %>
      </li>
      <li class="last">
        <%= link_to 'Delete', 
                    channel_post_path(@channel, post), 
                    :method => :delete, 
                    :confirm =>'are you sure?' %>
      </li>
    </ul>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rss</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
	<!-- <% if controller.class != LoginController %>
	<%= link_to 'Logout', login_path, :method => :delete %>
	<% end %> -->
</div>

<%= yield %>

</body>
</html>

app/views/login/show.html.erb
<h1>Login</h1>

<% if @login_error_msg %>
<div class="errors">
	<%= @login_error_msg %>
</div>
<% end %>

<%= form_tag login_path do |f|  %>
	<p>
		<label>Username:</label><br />
		<input type="text" name="username" />
    </p>
    <p>
    	<label>Password:</label><br />
    	<input type="password" name="password" />
    </p>
    <p>
    	<%= submit_tag 'Login' %>
    </p>
<% end %>

app/views/posts/_form.html.erb
<%= form_for [@post.channel, @post], :html => {:enctype => 'multipart/form-data'} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3><%= f.label :title %></h3>
    <%= f.text_field :title, :class => 'post_title_field' %>
  </div>
  <div class="field">
    <h3><%= f.label :content %><h3>
    <%= f.text_area :content, :class => 'post_content_field' %>
  </div>
  <div class="field">
    <h3>Upload a picture</h3>
    <%= file_field_tag :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
  <b>title:</b>
  <%= post.title %>
</p>

<p>
  <b>Content:</b>
  <%= post.title %>
</p>

<% if post.image %>
<p>
  <%= image_tag channel_post_image_path(post.channel, post) %>
</p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form' %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<%if notice %><p id="notice"><%= notice %></p> <% end %>

<%= render :partial => 'post', 
           :locals => {:post => @post} %>

<%= link_to 'Edit', edit_channel_post_path(@post.channel, @post) %> |
<%= link_to 'Back', channel_path(@post.channel) %>